server.port=${PORT:9090}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXP_MIN:480}

spring.mvc.pathmatch.matching-strategy=ant_path_matcher