server.port=${PORT:9090}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/alumnos_banda}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

app.jwt.secret=${JWT_SECRET:MI_SUPER_SECRET_LARGO_DE_32_CHARS_MINIMO_123456}
app.jwt.expiration-minutes=${JWT_EXP_MIN:480}

spring.mvc.pathmatch.matching-strategy=ant_path_matcher